### ISSUE TITLE
App collapsed when i play music from album. then share.

### ISSUE THREAD

**Issue by darewealth** [Crypto-Android-Apps/ACG-Player#45]
**Describe the bug**
When I play music through the album then I tried to share, the app collapse, then it shows the link I could share too.  

**To Reproduce**

1. Launch the app
2. Click on an album and click any music
3. Play the music and click 3 on the music you play
4. Then click share and see the error

**Expected behavior**
I expect that the music continues to play and there will be a pop up of where I can share the music too. And I don't expect the app to collapse.

**Screenshots**
https://youtu.be/QpqGzn6F4QU

**Smartphone.
 - Device: [itel]
 - OS: [6.1]
 - Version [2.6.5.3(20190531)]

### Log
```05-31 15:18:12.410 29438 29438 E AndroidRuntime: FATAL EXCEPTION: main
05-31 15:18:12.410 29438 29438 E AndroidRuntime: Process: top.geek_studio.chenlongcould.musicplayer.Common, PID: 29438
05-31 15:18:12.410 29438 29438 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.os.BaseBundle.getString(java.lang.String, java.lang.String)' on a null object reference
05-31 15:18:12.410 29438 29438 E AndroidRuntime: 	at top.geek_studio.chenlongcould.musicplayer.utils.OpEntry.getStringValue(SourceFile:1)
05-31 15:18:12.410 29438 29438 E AndroidRuntime: 	at top.geek_studio.chenlongcould.musicplayer.utils.SharedPreferenceProxy.getString(SourceFile:2)
05-31 15:18:12.410 29438 29438 E AndroidRuntime: 	at top.geek_studio.chenlongcould.musicplayer.fragment.MusicDetailFragment$NotLeakHandler.Tf(SourceFile:12)
05-31 15:18:12.410 29438 29438 E AndroidRuntime: 	at i.a.a.b.e.z.run(lambda)
05-31 15:18:12.410 29438 29438 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:739)
05-31 15:18:12.410 29438 29438 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
05-31 15:18:12.410 29438 29438 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
05-31 15:18:12.410 29438 29438 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5452)
05-31 15:18:12.410 29438 29438 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-31 15:18:12.410 29438 29438 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:781)
05-31 15:18:12.410 29438 29438 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:671)```

**Comment by AugustToko** [comment]
Does it work normally elsewhere?

**Comment by darewealth** [comment]
It doesn't work in any part of the app.

**Comment by AugustToko** [comment]
Upgrade to [ACG Player X](https://github.com/Crypto-Android-Apps/ACG-Player-X/releases)
