### ISSUE TITLE
ACG-Player v2.6.6.8(20190608); Certain actions acted in the trashcan caused the app to crash. 

### ISSUE THREAD

**Issue by HarryHeights** [Crypto-Android-Apps/ACG-Player#66]
**Describe the bug**
I'll try to be concise in my description of the bug. I performed certain actions in the trashcan and the app crashed.  I added a song to the trashcan. In the trashcan, I accessed the options(while in the trashcan), and there was an option to add a song(already in the trashcan) to the trashcan.  I tried it out, and nothing happened. I went ahead to delete the song. I left the trashcan and accessed it again, and the song I deleted was still there. I accessed the options menu and clicked "more info" and the app crashed. 

**To Reproduce**

1. Add a song(you are willing to lose) to the trashcan
2. Access the trashcan. It is located in "Playlists"
3. In the trashcan, access the options menu.
4. Select the "drop to trashcan" option.
5. Access the options menu again. But this time, delete the song.
6. Exit the trashcan, and access it again. You will find the song you deleted still there.
7. Access the options menu and select the "more info" option.
8. See error.

**Expected behavior**
Firstly, I didn't expect the option "drop to trashcan" to still be available in the trashcan page. But even if it was possible for it(the option) to be there, I expected a toast message saying that the song was already in the trashcan.  
Secondly, I expected that after I deleted a song from the trashcan (even after the stunt I performed), it should no longer be available in the trashcan. 

**Screen recording**
https://youtu.be/olpTuOPTZpk

**Test Environment:**
 - Device: Redmi Note 5 Pro
 - OS: Android 9.0
 - Software Version: ACG-Player v2.6.6.8(20190608)

**Logcat**

``` java.lang.AssertionError: impossible
	at java.lang.Enum$1.create(Enum.java:272)
	at java.lang.Enum$1.create(Enum.java:262)
	at libcore.util.BasicLruCache.get(BasicLruCache.java:58)
	at java.lang.Enum.getSharedConstants(Enum.java:289)
	at java.lang.Enum.valueOf(Enum.java:244)
	at java.io.ObjectInputStream.readEnum(ObjectInputStream.java:1745)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:373)
	at android.os.Parcel.readSerializable(Parcel.java:2935)
	at android.os.Parcel.readValue(Parcel.java:2722)
	at android.os.Parcel.readArrayMapInternal(Parcel.java:3045)
	at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:288)
	at android.os.BaseBundle.unparcel(BaseBundle.java:232)
	at android.os.BaseBundle.getSerializable(BaseBundle.java:1236)
	at android.os.Bundle.getSerializable(Bundle.java:1034)
	at com.sothree.slidinguppanel.SlidingUpPanelLayout.onRestoreInstanceState(SourceFile:3)
	at android.view.View.dispatchRestoreInstanceState(View.java:18635)
	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3823)
	at android.view.View.restoreHierarchyState(View.java:18613)
	at b.o.a.i.restoreViewState(SourceFile:2)
	at b.o.a.x.a(SourceFile:169)
	at b.o.a.x.i(SourceFile:9)
	at b.o.a.x.l(SourceFile:13)
	at b.o.a.x.Wb(SourceFile:2)
	at b.o.a.x.dispatchActivityCreated(SourceFile:3)
	at b.o.a.k.onStart(SourceFile:6)
	at b.c.a.n.onStart(SourceFile:1)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1392)
	at android.app.Activity.performStart(Activity.java:7252)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:2970)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1831)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:201)
	at android.app.ActivityThread.main(ActivityThread.java:6810)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
Caused by: java.lang.NoSuchMethodException: values []
	at java.lang.Class.getMethod(Class.java:2068)
	at java.lang.Class.getDeclaredMethod(Class.java:2047)
	at java.lang.Enum$1.create(Enum.java:268)
	... 40 more

```

**Comment by AugustToko** [comment]
Sorry, the trash can is very unstable now. I currently only store data in memory and do not perform persistence operations. I will fix this later.
