### ISSUE TITLE
ACG-Player v2.6.8.7(20190619); A crash occurs when I try to reorganize the music tabs. 

### ISSUE THREAD

**Issue by HarryHeights** [Crypto-Android-Apps/ACG-Player#75]
I'm experiencing a sort of UI issue in the latest release. When I launch the app, the bottom part of it is cut out. This isn't an issue of the screen size optimization because the necessary elements are still there. I just can't see them. I have to perform certain swipe up activities before it becomes available. Please try to fix that. But. that's not the main reason for this issue. 

**Describe the bug**
On ACG-Player, it is possible to close the menu tabs, and also restore them. The idea isn't a bad one at all. However, there's an error that occurs when I perform this operation. 
I closed all the menus on the app. I exited the app after. When I launched the app, I decided to add the menus again. I started with the music tab. However, I tried to put the playlist tab next and the app crashed. 

** Steps To Reproduce**

1. Tab and hold a tab to reveal the option to close
2. Perform the action(close) for all the tabs
3. Exit the app
4. Launch the app
5. Click on the plus (+) icon to add the tabs back
6. Add any other tab aside from playlist first. 
7. Then add the playlist tab next
8. See error. 

**Expected behavior**
When I carried out this operation, the reason behind it was to organise the tabs the way I wanted it. I expected that I could add tabs in any order I desired. 

**Screen recording**
https://youtu.be/cqNg_Lbf5Ss

**Test Environment**

 - Device: Redmi Note 5 Pro
 - OS: Android 9.0
 - Software version: ACG-Player v2.6.8.7(20190619)

**Logcat**

``` java.lang.NullPointerException: Attempt to read from field 'java.util.List top.geek_studio.chenlongcould.musicplayer.fragment.PlayListFragment.mPlayListItemList' on a null object reference
	at top.geek_studio.chenlongcould.musicplayer.activity.main.MainActivity.setSubTitleType(SourceFile:1)
	at top.geek_studio.chenlongcould.musicplayer.activity.main.MainActivity.access$300(SourceFile:1)
	at top.geek_studio.chenlongcould.musicplayer.activity.main.MainActivity$3.onPageSelected(SourceFile:11)
	at androidx.viewpager.widget.ViewPager.ya(SourceFile:6)
	at androidx.viewpager.widget.ViewPager.a(SourceFile:67)
	at androidx.viewpager.widget.ViewPager.a(SourceFile:59)
	at androidx.viewpager.widget.ViewPager.a(SourceFile:43)
	at androidx.viewpager.widget.ViewPager.Ca(SourceFile:2)
	at top.geek_studio.chenlongcould.musicplayer.activity.main.MainActivity.e(SourceFile:51)
	at h.a.a.b.a.e.p.onMenuItemClick(Unknown Source:2)
	at android.widget.PopupMenu$1.onMenuItemSelected(PopupMenu.java:105)
	at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:776)
	at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:148)
	at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:923)
	at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:913)
	at com.android.internal.view.menu.MenuPopup.onItemClick(MenuPopup.java:128)
	at android.widget.AdapterView.performItemClick(AdapterView.java:318)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1192)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3184)
	at android.widget.AbsListView$3.run(AbsListView.java:4166)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:201)
	at android.app.ActivityThread.main(ActivityThread.java:6810)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
```

**Comment by AugustToko** [comment]
Thank you for your report. I am very surprised that the ACG PLAYER is based on Android 9.0 on MIUI, and there are a lot of problems, sliding stuck, UI misalignment, and black stripes at the bottom.

I can close the tab and I will fix it. ACG PLAYER's compatibility with MIUI I have been adjusting recently

**Comment by AugustToko** [comment]
I can't do it, I might get rid of the new UI, (many blur features)

**Comment by HarryHeights** [comment]
> Thank you for your report. I am very surprised that the ACG PLAYER is based on Android 9.0 on MIUI, and there are a lot of problems, sliding stuck, UI misalignment, and black stripes at the bottom.
> 
> I can close the tab and I will fix it. ACG PLAYER's compatibility with MIUI I have been adjusting recently

I hope you fix it. There were few issues when I still used Android 8.1

**Comment by AugustToko** [comment]
> > Thank you for your report. I am very surprised that the ACG PLAYER is based on Android 9.0 on MIUI, and there are a lot of problems, sliding stuck, UI misalignment, and black stripes at the bottom.
> > I can close the tab and I will fix it. ACG PLAYER's compatibility with MIUI I have been adjusting recently
> 
> I hope you fix it. There were few issues when I still used Android 8.1

I fixed the problem at the bottom and watched the latest version (release page)

**Comment by HarryHeights** [comment]
The UI issue has been fixed.
