### ISSUE TITLE
The app crashed on first launch. 

### ISSUE THREAD

**Issue by darewealth** [Crypto-Android-Apps/ACG-Player#83]
**Describe the bug**
After I had installed the app and launched I granted the permission and after a few seconds, the app crashed

**To Reproduce**
1. Install the app
2. Launch the app
3. grant the permission 
4. wait a few seconds and see the error

**Expected behavior**
I expect to use the app without any crash.

**Screenshots**
https://youtu.be/D5-yezNtf2g

**Smartphone**
 - Device: [itel]
 - OS: [6.1]
 - Version [2.6.9.4]

### Log
```FATAL EXCEPTION: IntentService[DBArtSync]
06-23 08:24:24.367 26974 27233 E AndroidRuntime: Process: top.geek_studio.chenlongcould.musicplayer.Common, PID: 26974
06-23 08:24:24.367 26974 27233 E AndroidRuntime: org.litepal.exceptions.LitePalSupportException: no such table: artistartpath (code 1): , while compiling: SELECT * FROM artistartpath ORDER BY id
06-23 08:24:24.367 26974 27233 E AndroidRuntime: 	at org.litepal.crud.DataHandler.query(SourceFile:22)
06-23 08:24:24.367 26974 27233 E AndroidRuntime: 	at org.litepal.crud.QueryHandler.onFindAll(SourceFile:6)
06-23 08:24:24.367 26974 27233 E AndroidRuntime: 	at org.litepal.Operator.findAll(SourceFile:6)
06-23 08:24:24.367 26974 27233 E AndroidRuntime: 	at org.litepal.Operator.findAll(SourceFile:1)
06-23 08:24:24.367 26974 27233 E AndroidRuntime: 	at top.geek_studio.chenlongcould.musicplayer.DBArtSync.handleActionSyncArtist(SourceFile:11)
06-23 08:24:24.367 26974 27233 E AndroidRuntime: 	at top.geek_studio.chenlongcould.musicplayer.DBArtSync.onHandleIntent(SourceFile:5)
06-23 08:24:24.367 26974 27233 E AndroidRuntime: 	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:66)
06-23 08:24:24.367 26974 27233 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
06-23 08:24:24.367 26974 27233 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
06-23 08:24:24.367 26974 27233 E AndroidRuntime: 	at android.os.HandlerThread.run(HandlerThread.java:61)
06-23 08:24:24.367 26974 27233 E AndroidRuntime: Caused by: android.database.sqlite.SQLiteException: no such table: artistartpath (code 1): , while compiling: SELECT * FROM artistartpath ORDER BY id
06-23 08:24:24.367 26974 27233 E AndroidRuntime: 	at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
06-23 08:24:24.367 26974 27233 E AndroidRuntime: 	at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:887)
06-23 08:24:24.367 26974 27233 E AndroidRuntime: 	at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:498)
06-23 08:24:24.367 26974 27233 E AndroidRuntime: 	at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
06-23 08:24:24.367 26974 27233 E AndroidRuntime: 	at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
06-23 08:24:24.367 26974 27233 E AndroidRuntime: 	at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
06-23 08:24:24.367 26974 27233 E AndroidRuntime: 	at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:44)
06-23 08:24:24.367 26974 27233 E AndroidRuntime: 	at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1316)
06-23 08:24:24.367 26974 27233 E AndroidRuntime: 	at android.database.sqlite.SQLiteDatabase.queryWithFactory(SQLiteDatabase.java:1163)
06-23 08:24:24.367 26974 27233 E AndroidRuntime: 	at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1034)
06-23 08:24:24.367 26974 27233 E AndroidRuntime: 	at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1240)
06-23 08:24:24.367 26974 27233 E AndroidRuntime: 	at org.litepal.crud.DataHandler.query(SourceFile:6)```

**Comment by AugustToko** [comment]
Upgrade to [ACG Player X](https://github.com/Crypto-Android-Apps/ACG-Player-X/releases)
