### ISSUE TITLE
The app crashed when i changed theme mode 2 or 3 times.

### ISSUE THREAD

**Issue by darewealth** [Crypto-Android-Apps/ACG-Player#84]
**Describe the bug**
I tried to change the app theme to dark and I still decide to change back to light and when I did the app crashed.

**To Reproduce**
1. Launch the app
2. Click on menu 
3. Click on dark mode and change it like 3 times

**Expected behavior**
I expect to use this function without an error 

**Screenshots**
https://youtu.be/1kYKBOlC33Q

**Smartphone**
 - Device: [Gionee X1]
 - OS: [7.0]
 - Version [2.6.9.4]

### Log
```06-23 08:30:35.746 31183 31183 E AndroidRuntime: FATAL EXCEPTION: main
06-23 08:30:35.746 31183 31183 E AndroidRuntime: Process: top.geek_studio.chenlongcould.musicplayer.Common, PID: 31183
06-23 08:30:35.746 31183 31183 E AndroidRuntime: android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.BinderProxy@f9e9dfa is not valid; is your activity running?
06-23 08:30:35.746 31183 31183 E AndroidRuntime: 	at android.view.ViewRootImpl.setView(ViewRootImpl.java:567)
06-23 08:30:35.746 31183 31183 E AndroidRuntime: 	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:313)
06-23 08:30:35.746 31183 31183 E AndroidRuntime: 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:85)
06-23 08:30:35.746 31183 31183 E AndroidRuntime: 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3177)
06-23 08:30:35.746 31183 31183 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2482)
06-23 08:30:35.746 31183 31183 E AndroidRuntime: 	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4092)
06-23 08:30:35.746 31183 31183 E AndroidRuntime: 	at android.app.ActivityThread.-wrap15(ActivityThread.java)
06-23 08:30:35.746 31183 31183 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1351)
06-23 08:30:35.746 31183 31183 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
06-23 08:30:35.746 31183 31183 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
06-23 08:30:35.746 31183 31183 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5452)
06-23 08:30:35.746 31183 31183 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-23 08:30:35.746 31183 31183 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:781)
06-23 08:30:35.746 31183 31183 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:671)```

**Comment by AugustToko** [comment]
Upgrade to [ACG Player X](https://github.com/Crypto-Android-Apps/ACG-Player-X/releases)
